---

# Test nginx configuration. nginx -t returns a non-zero error code on config failures
- name: Test configuration
  ansible.builtin.command: nginx -t
  register: conf_ok
  failed_when: conf_ok.rc != 0
  notify: Restart nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: conf_ok.rc == 0
